import type { UserRole } from "@/types/auth";
import { ROUTES } from "@/constants/routes";

export const ROLE_DASHBOARD_ROUTE: Record<UserRole, string> = {
  ADMIN: ROUTES.DASHBOARD,
  HR_MANAGER: ROUTES.HR_DASHBOARD,
  EMPLOYEE: ROUTES.DASHBOARD,
  APPLICANT: ROUTES.DASHBOARD,
  UNKNOWN: ROUTES.LOGIN,
};

export const ROLE_ALLOWED_ROUTES: Record<UserRole, string[]> = {
  ADMIN: [
    ROUTES.DASHBOARD,
    ROUTES.HR_DASHBOARD,
    ROUTES.HR_ATTENDANCE,
    ROUTES.HR_EMPLOYEES,
    ROUTES.HR_APPLICATIONS,
    ROUTES.HR_RECRUITMENT,
    ROUTES.HR_REPORTS,
    ROUTES.HR_SHORTLIST,
    ROUTES.HR_LEAVE,
    ROUTES.RECRUITMENT_JOB_POSTINGS,
    ROUTES.RECRUITMENT_APPLICATIONS,
    ROUTES.RECRUITMENT_SHORTLIST,
  ],
  HR_MANAGER: [
    ROUTES.HR_DASHBOARD,
    ROUTES.HR_ATTENDANCE,
    ROUTES.HR_EMPLOYEES,
    ROUTES.HR_APPLICATIONS,
    ROUTES.HR_RECRUITMENT,
    ROUTES.HR_REPORTS,
    ROUTES.HR_SHORTLIST,
    ROUTES.HR_LEAVE,
    ROUTES.RECRUITMENT_JOB_POSTINGS,
    ROUTES.RECRUITMENT_APPLICATIONS,
    ROUTES.RECRUITMENT_SHORTLIST,
  ],
  EMPLOYEE: [ROUTES.DASHBOARD],
  APPLICANT: [ROUTES.DASHBOARD],
  UNKNOWN: [],
};
